### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MyNewBie** [Allu2/TeeBot2#1]
> > > C:\Users\MyOffice\Desktop\TeeBot\Bot.py
> > >   File "< stdin >", line 1
> > >     C:\Users\MyOffice\Desktop\TeeBot\Bot.py
> > >      ^
> > > SyntaxError: invalid syntax

**Comment by Allu2** [comment]
Could you post the whole command you are running and the python version you are using?

**Comment by MyNewBie** [comment]
Python32 , I runed python command prompt(python.exe) then I wrote this : C:\Users\MyOffice\Desktop\TeeBot\Bot.py

**Comment by Allu2** [comment]
To run this you need to run it in fashion similar to:
python.exe C:\Users\MyOffice\Desktop\TeeBot\Bot.py

**Comment by MyNewBie** [comment]
idk maybe this can help : http://image.noelshack.com/fichiers/2015/42/1444657757-capture231.png

**Comment by Allu2** [comment]
Yeah you're trying to run it in python console where you should be trying to run it using python on regular console ^^
Maybe this will help http://puu.sh/kHz9X/d469bccccb.png
